/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutFoundationRouteImport } from './routes/about-foundation'
import { Route as EducationRouteImport } from './routes/education'
import { Route as EnvironmentRuralRegenerationRouteImport } from './routes/environment-rural-regeneration'
import { Route as HealthcareSocialWelfareRouteImport } from './routes/healthcare-social-welfare'
import { Route as SitaSamahitSthalRouteImport } from './routes/sita-samahit-sthal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFoundationRoute = AboutFoundationRouteImport.update({
  id: '/about-foundation',
  path: '/about-foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRuralRegenerationRoute =
  EnvironmentRuralRegenerationRouteImport.update({
    id: '/environment-rural-regeneration',
    path: '/environment-rural-regeneration',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthcareSocialWelfareRoute = HealthcareSocialWelfareRouteImport.update({
  id: '/healthcare-social-welfare',
  path: '/healthcare-social-welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const SitaSamahitSthalRoute = SitaSamahitSthalRouteImport.update({
  id: '/sita-samahit-sthal',
  path: '/sita-samahit-sthal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-foundation': typeof AboutFoundationRoute
  '/education': typeof EducationRoute
  '/environment-rural-regeneration': typeof EnvironmentRuralRegenerationRoute
  '/healthcare-social-welfare': typeof HealthcareSocialWelfareRoute
  '/sita-samahit-sthal': typeof SitaSamahitSthalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-foundation': typeof AboutFoundationRoute
  '/education': typeof EducationRoute
  '/environment-rural-regeneration': typeof EnvironmentRuralRegenerationRoute
  '/healthcare-social-welfare': typeof HealthcareSocialWelfareRoute
  '/sita-samahit-sthal': typeof SitaSamahitSthalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-foundation': typeof AboutFoundationRoute
  '/education': typeof EducationRoute
  '/environment-rural-regeneration': typeof EnvironmentRuralRegenerationRoute
  '/healthcare-social-welfare': typeof HealthcareSocialWelfareRoute
  '/sita-samahit-sthal': typeof SitaSamahitSthalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-foundation'
    | '/education'
    | '/environment-rural-regeneration'
    | '/healthcare-social-welfare'
    | '/sita-samahit-sthal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-foundation'
    | '/education'
    | '/environment-rural-regeneration'
    | '/healthcare-social-welfare'
    | '/sita-samahit-sthal'
  id:
    | '__root__'
    | '/'
    | '/about-foundation'
    | '/education'
    | '/environment-rural-regeneration'
    | '/healthcare-social-welfare'
    | '/sita-samahit-sthal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutFoundationRoute: typeof AboutFoundationRoute
  EducationRoute: typeof EducationRoute
  EnvironmentRuralRegenerationRoute: typeof EnvironmentRuralRegenerationRoute
  HealthcareSocialWelfareRoute: typeof HealthcareSocialWelfareRoute
  SitaSamahitSthalRoute: typeof SitaSamahitSthalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-foundation': {
      id: '/about-foundation'
      path: '/about-foundation'
      fullPath: '/about-foundation'
      preLoaderRoute: typeof AboutFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment-rural-regeneration': {
      id: '/environment-rural-regeneration'
      path: '/environment-rural-regeneration'
      fullPath: '/environment-rural-regeneration'
      preLoaderRoute: typeof EnvironmentRuralRegenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare-social-welfare': {
      id: '/healthcare-social-welfare'
      path: '/healthcare-social-welfare'
      fullPath: '/healthcare-social-welfare'
      preLoaderRoute: typeof HealthcareSocialWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sita-samahit-sthal': {
      id: '/sita-samahit-sthal'
      path: '/sita-samahit-sthal'
      fullPath: '/sita-samahit-sthal'
      preLoaderRoute: typeof SitaSamahitSthalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutFoundationRoute: AboutFoundationRoute,
  EducationRoute: EducationRoute,
  EnvironmentRuralRegenerationRoute: EnvironmentRuralRegenerationRoute,
  HealthcareSocialWelfareRoute: HealthcareSocialWelfareRoute,
  SitaSamahitSthalRoute: SitaSamahitSthalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
